import AuthContext from '@/context/AuthContext';
import type { Metadata } from 'next';
import { Inter, Libre_Baskerville } from 'next/font/google';
import '@/styles/global.css';

import Layout from '@/components/Layout';
import SWRConfigContext from '@/context/SWRConfigContext';

const inter = Inter({ subsets: ['latin'], display: 'swap', variable: '--font-inter' });
const libre = Libre_Baskerville({
  weight: '700',
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-libre',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="h-full">
      <body className={`${inter.className} ${libre.variable} h-full`}>
        <AuthContext>
          <Layout>
            <main className="max-w-[480px] flex-[1]">
              <SWRConfigContext>{children} </SWRConfigContext>
            </main>
          </Layout>
        </AuthContext>
      </body>
    </html>
  );
}
